---
Name: goldfinch-basement
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Basement\Extensions\SiteConfigExtension

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Goldfinch\Basement\Extensions\BaseElementExtension
