---
Name: goldfinch-basement
After:
  - '#goldfinch-formhandler'
  - '#goldfinch-instsupply'
  - '#goldfinch-cookieconsent'
---

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Goldfinch\Basement\Extensions\ContentControllerExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Basement\Extensions\SiteConfigExtension

SilverStripe\CMS\Model\SiteTree:
  meta_generator: ""
  page_title_separator: "|"
  extensions:
    - Goldfinch\Basement\Extensions\SiteTreeExtension

Page:
  extensions:
    - Goldfinch\Basement\Extensions\PageExtension

# to avoid issues with http when it should be https (admin.types.graphql, assets, bundle etc.)
SilverStripe\Control\Director:
  alternate_base_url: '`SS_BASE_URL`'
