---
Name: goldfinch-basement
After:
  - '#rootroutes'
  - '#coreroutes'
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Basement\Extensions\SiteConfigExtension

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Goldfinch\Basement\Extensions\BaseElementExtension
