---
Name: goldfinch-basement
After:
  - '#goldfinch-formhandler'
  - '#goldfinch-instsupply'
  - '#goldfinch-cookieconsent'
  - '#elemental'
  - '#elementalcache'
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Basement\Extensions\SiteConfigExtension

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Goldfinch\Basement\Extensions\BaseElementExtension
