---
Name: goldfinch-basement
After:
  - '#goldfinch-formhandler'
  - '#goldfinch-instsupply'
  - '#goldfinch-cookieconsent'
  - '#elemental'
  - '#elementalcache'
---

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Goldfinch\Basement\Extensions\ContentControllerExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Basement\Extensions\SiteConfigExtension

SilverStripe\CMS\Model\SiteTree:
  meta_generator: ""
  page_title_separator: "|"
  extensions:
    - Goldfinch\Basement\Extensions\SiteTreeExtension

Page:
  extensions:
    - Goldfinch\Basement\Extensions\PageExtension

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Goldfinch\Basement\Extensions\BaseElementExtension
